---
- name: Set templatized Kapacitor configuration
  template:
    src: kapacitor.conf.j2
    dest: "/etc/kapacitor/kapacitor.conf"
    force: yes
    backup: yes
    owner: kapacitor
    group: kapacitor
    mode: 0744
  notify:
    - restart kapacitord
  when: kapacitor_template_configuration

- name: Start the Kapacitor service
  service:
    name: kapacitor
    state: started
    enabled: yes
  when: kapacitor_start_service

- name: Wait for the Kapacitor API to be up
  wait_for:
    host: "{{ kapacitor_http_bind_host | default('127.0.0.1') }}"
    port: "{{ kapacitor_http_bind_port }}"
    timeout: 60
  when: kapacitor_start_service

- name: Check for existing tasks
  command: kapacitor list tasks
  register: kapacitor_list_tasks

- debug:
    var: kapacitor_list_tasks

- name: Copy specified TICKscript scripts to remote host
  copy:
    src: "{{ item.tick }}"
    dest: /tmp/{{ item.tick }}
  when: kapacitor_list_tasks.stdout.find("{{ item.name }}") == -1
  with_items: "{{ kapacitor_tasks_to_enable }}"

- name: Define specified tasks
  command: kapacitor define -name {{ item.name }} -type {{ item.type }} -tick /tmp/{{ item.tick }} -dbrp {{ item.dbrp }}
  when: kapacitor_list_tasks.stdout.find("{{ item.name }}") == -1
  with_items: "{{ kapacitor_tasks_to_enable }}"

- name: Enable specified tasks
  command: kapacitor enable {{ item.name }}
  when: kapacitor_list_tasks.stdout.find("{{ item.name }}") == -1
  with_items: "{{ kapacitor_tasks_to_enable }}"
